sudo: false
language: python
python:
    - "3.5"
python:
- 2.7
- 3.4
- 3.5

install:
- pip install \
    `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"] + META["install_requires"]))'`

script: make test
